INSERT INTO cidade(nome, estado_id) VALUES ('Rio Branco', 2);
INSERT INTO cidade(nome, estado_id) VALUES ('Maceió', 3);
INSERT INTO cidade(nome, estado_id) VALUES ('Macapá', 4);
INSERT INTO cidade(nome, estado_id) VALUES ('Manaus', 5);
INSERT INTO cidade(nome, estado_id) VALUES ('Salvador', 6);
INSERT INTO cidade(nome, estado_id) VALUES ('Fortaleza', 7);
INSERT INTO cidade(nome, estado_id) VALUES ('Brasília', 8);
INSERT INTO cidade(nome, estado_id) VALUES ('Vitória', 9);
INSERT INTO cidade(nome, estado_id) VALUES ('Goiânia', 10);
INSERT INTO cidade(nome, estado_id) VALUES ('São Luís', 11);
INSERT INTO cidade(nome, estado_id) VALUES ('Cuiabá', 12);
INSERT INTO cidade(nome, estado_id) VALUES ('Campo Grande', 13);
INSERT INTO cidade(nome, estado_id) VALUES ('Belo Horizonte', 14);
INSERT INTO cidade(nome, estado_id) VALUES ('Belém', 15);
INSERT INTO cidade(nome, estado_id) VALUES ('João Pessoa', 16);
INSERT INTO cidade(nome, estado_id) VALUES ('Curitiba', 17);
INSERT INTO cidade(nome, estado_id) VALUES ('Recife', 18);
INSERT INTO cidade(nome, estado_id) VALUES ('Teresina', 19);
INSERT INTO cidade(nome, estado_id) VALUES ('Rio de Janeiro', 20);
INSERT INTO cidade(nome, estado_id) VALUES ('Natal', 21);
INSERT INTO cidade(nome, estado_id) VALUES ('Porto Alegre', 22);
INSERT INTO cidade(nome, estado_id) VALUES ('Porto Velho', 23);
INSERT INTO cidade(nome, estado_id) VALUES ('Boa Vista', 24);
INSERT INTO cidade(nome, estado_id) VALUES ('Florianópolis', 25);
INSERT INTO cidade(nome, estado_id) VALUES ('São Paulo', 26);
INSERT INTO cidade(nome, estado_id) VALUES ('Aracaju', 27);
INSERT INTO cidade(nome, estado_id) VALUES ('Palmas', 28);
